baseurl = "/"
title = "Sridhar's Blog!"
languageCode = "en-us"
#theme = "newsroom"
theme = "hextra"
locale = "en_US"
publishDir = "public"

[pagination]
disableAliases = false
pagerSize = 10
path = 'page'

author = "Sridhar"
canonifyurls = true
twitter = "@ssathya"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[taxonomies]
  category = "categories"
  tag = "tags"
